// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.getit.todoapp.domain;

import com.getit.todoapp.domain.UserinfoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserinfoDataOnDemand_Roo_Configurable {
    
    declare @type: UserinfoDataOnDemand: @Configurable;
    
}
